<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.5/build/pure-min.css" integrity="sha384-LTIDeidl25h2dPxrB2Ekgc9c7sEC3CWGM6HeFmuDNUjX76Ert4Z4IY714dhZHPLd" crossorigin="anonymous">
<link rel="stylesheet" href="/css/styles.css" type="text/css"/>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<%@include  file="const/head-menu.html" %>

</head>
<body>
    <center>
    <div id="layout" class="pure-g">
        <div class="pure-u-1">
        <div class="entries">
            <form:form action="${functionName}" modelAttribute="entryDto">
            <br>
                <div> ${message} </div><br>

                    <table class="pure-table pure-table-horizontal">
  
                        <form:input path="id" type="hidden" value="${entryDto.id}"/>                            
                        <tr>
                            <div class="pure-control-group">
                                <td><label> Title: </label></td>
                                <td>
                                    <form:input type="text" class="pure-input-1" path="title" value="${entryDto.title}"/>
                                    <form:errors path="title" cssClass="error" />
                                </td>
                            </div>
                        </tr>
                        <tr>
                            <div class="pure-control-group">
                                <td>Time stamp:</td>
                                <td><form:input type="text" class="pure-input-1" path="timestamp" value="${entryDto.timestamp}" placeholder="<autogenerated>" readonly="true" disbaled="true"/></td>
                            </div>
                        </tr>
                        <tr>                
                            <div class="pure-control-group">
                                <td><label>Category:</label></td>  
                                <td>
                                    <form:select path="category">
                                        <form:option label="Choose category" value="${null}"/>
                                        <c:forEach var="option" items="${categories}">
                                            <form:option value="${option.displayName}"/>
                                        </c:forEach>
                                    </form:select>
                                    <form:errors path="category" cssClass="error" />

                                
                                </td>
                            </div>
                        </tr>
                        <tr>
                            <div class="pure-control-group">
                                <td>Content: </td> 
                                <td max-width="50">
                                    <form:textarea path="content" rows="7" cols="25" value="${entryDto.content}"/>
                                    <form:errors path="content" cssClass="error" />
                                </td>
                            </div>
                        </tr>
                
                        
                    </table>

                    <input type="submit">                
                    
            </form:form>
        </div>
        </div>
    </div>    
    </center>

</body>
<%@include  file="const/footer.html" %>
</html>