DROP TABLE JOURNAL_ENTRY IF EXISTS;
CREATE TABLE JOURNAL_ENTRY (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    timestamp TIMESTAMP,
    title VARCHAR(400) NOT NULL,
    category VARCHAR(40) NOT NULL,
    content VARCHAR(2000) NULL,
    locale VARCHAR(40) NULL
);